### ISSUE TITLE
Error in multisessionUssd

### ISSUE THREAD

**Issue by bipinkrish** [EddieKamau/ussd_advanced#17]
I got this when i used `UssdAdvanced.multisessionUssd()`

```
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): Failed to handle method call
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toString()' on a null object reference
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at com.phan_tech.ussd_advanced.USSDController.isAccessibilityServicesEnable(USSDController.kt:244)
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at com.phan_tech.ussd_advanced.USSDController.verifyAccessibilityAccess(USSDController.kt:227)
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at com.phan_tech.ussd_advanced.USSDController.callUSSDInvoke(USSDController.kt:112)
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at com.phan_tech.ussd_advanced.UssdAdvancedPlugin.multisessionUssd(UssdAdvancedPlugin.kt:272)
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at com.phan_tech.ussd_advanced.UssdAdvancedPlugin.onMethodCall(UssdAdvancedPlugin.kt:158)
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at android.os.Looper.loopOnce(Looper.java:240)
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at android.os.Looper.loop(Looper.java:351)
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at android.app.ActivityThread.main(ActivityThread.java:8377)
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/MethodChannel#method.com.phan_tech/ussd_advanced(17316): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

I have all the permissions needed and have no problem using `UssdAdvanced.sendAdvancedUssd()` and also in Mainefest

```
<application>
....
 <!-- Multi USSD Service -->
        <service
            android:name="com.phan_tech.ussd_advanced.USSDServiceKT"
            android:permission="android.permission.BIND_ACCESSIBILITY_SERVICE"
            android:exported="false">
            <intent-filter>
                <action android:name="android.accessibilityservice.AccessibilityService" />
            </intent-filter>
            <meta-data
                android:name="android.accessibilityservice"
                android:resource="@xml/ussd_service" />
        </service>
...
</application>
```

**Comment by CairoSergio** [comment]
did u find the solution?

**Comment by bipinkrish** [comment]
> did u find the solution?

No
