### ISSUE TITLE
Failed to handle method call

### ISSUE THREAD

**Issue by jeanclaudesoft** [EddieKamau/ussd_advanced#19]
I have an error when calling UssdAdvanced.sendUssd()
This is the full error 

E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): Failed to handle method call
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): java.lang.IllegalArgumentException: Unsupported value: 'kotlin.Unit' of type 'class kotlin.Unit'
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:61)
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:272)
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): 	at com.phan_tech.ussd_advanced.UssdAdvancedPlugin.onMethodCall(UssdAdvancedPlugin.kt:120)
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): 	at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#method.com.phan_tech/ussd_advanced(11576): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/flutter (11576): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Unsupported value: 'kotlin.Unit' of type 'class kotlin.Unit', null, java.lang.IllegalArgumentException: Unsupported value: 'kotlin.Unit' of type 'class kotlin.Unit'
E/flutter (11576): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/flutter (11576): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:61)
E/flutter (11576): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:272)
E/flutter (11576): 	at com.phan_tech.ussd_advanced.UssdAdvancedPlugin.onMethodCall(UssdAdvancedPlugin.kt:120)
E/flutter (11576): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter (11576): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter (11576): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (11576): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (11576): 	at android.os.Handler.handleCallback(Handler.java:958)
E/flutter (11576): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (11576): 	at android.os.Looper.loopOnce(Looper.java:205)
E/flutter (11576): 	at android.os.Looper.loop(Looper.java:294)
E/flutter (11576): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/flutter (11576): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (11576): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/flutter (11576): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/flutter (11576): )
E/flutter (11576): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter (11576): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (11576): <asynchronous suspension>
E/flutter (11576): #2      UssdAdvanced.sendUssd (package:ussd_advanced/ussd_advanced.dart:15:5)
E/flutter (11576): <asynchronous suspension>

**Comment by rutatiina** [comment]
Am getting the same error.
It throws that error and then makes the ussd
