### ISSUE TITLE
sendAdvancedUssd always throw "Unhandled Exception: PlatformException(ussd_plugin_ussd_execution_failure, USSD_RETURN_FAILURE, null, null)"

### ISSUE THREAD

**Issue by blackbusters** [EddieKamau/ussd_advanced#4]
Hi..

I tried using sendAdvancedUssd with this code :
`        SimData simData = await SimDataPlugin.getSimData();
        for (var s in simData.cards) {
          var str = await UssdAdvanced.sendAdvancedUssd(code: "*808#", subscriptionId: s.subscriptionId);
          print(str);
        }
`

but it always throw me an error :
E/flutter (19903): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(ussd_plugin_ussd_execution_failure, USSD_RETURN_FAILURE, null, null)
E/flutter (19903): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:589)
E/flutter (19903): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167)
E/flutter (19903): <asynchronous suspension>
E/flutter (19903): #2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:873)
E/flutter (19903): <asynchronous suspension>
E/flutter (19903): #3      UssdAdvanced.sendAdvancedUssd (package:ussd_advanced/ussd_advanced.dart:18)
E/flutter (19903): <asynchronous suspension>

Currently I'm using Flutter 2.8.1 and targeting android sdk 30.

Is there anything i can do to fix this?

**Comment by ALI-SAMPSON** [comment]
I'm facing the same issue here.

**Comment by Zeeshan90** [comment]
I'm also facing the same issue.

**Comment by sakib556** [comment]
I'm also facing the same issue.

**Comment by tejas1106** [comment]
I'm also facing the same error. Any solution to this?

**Comment by K0M4L** [comment]
I'm also facing the same issue. Any solution?

**Comment by pkitatta** [comment]
Same problem with me.

**Comment by Manuel2u** [comment]
i don't think there is an easy solution to it
because its blocked by the device manufacturers (affects certain devices)
unless you have root access to the device
