### ISSUE TITLE
Unhandled Exception: PlatformException(ussd_plugin_ussd_execution_failure, USSD_RETURN_FAILURE, null, null)

### ISSUE THREAD

**Issue by aleelo** [EddieKamau/ussd_advanced#5]
E/flutter (16893): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(ussd_plugin_ussd_execution_failure, USSD_RETURN_FAILURE, null, null)
E/flutter (16893): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (16893): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
E/flutter (16893): <asynchronous suspension>
E/flutter (16893): #2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:870:15)
E/flutter (16893): <asynchronous suspension>
E/flutter (16893): #3      UssdAdvanced.sendAdvancedUssd (package:ussd_advanced/ussd_advanced.dart:21:30)
E/flutter (16893): <asynchronous suspension>
E/flutter (16893): #4      _MyHomePageState.build._incrementCounter (package:easy_pay/main.dart:71:24)
E/flutter (16893): <asynchronous suspension>

I get this error when i call sendAdvancedUssd method. 
please solve this issue asap we are waiting.
thank you.

**Comment by Zeeshan90** [comment]
Getting the same error can any one help here whats the issue?

**Comment by tejas1106** [comment]
Same error. Any solution for this?

**Comment by amotalles** [comment]
> E/flutter (16893): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(ussd_plugin_ussd_execution_failure, USSD_RETURN_FAILURE, null, null) E/flutter (16893): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7) E/flutter (16893): #1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18) E/flutter (16893): E/flutter (16893): #2 Future.timeout. (dart:async/future_impl.dart:870:15) E/flutter (16893): E/flutter (16893): #3 UssdAdvanced.sendAdvancedUssd (package:ussd_advanced/ussd_advanced.dart:21:30) E/flutter (16893): E/flutter (16893): #4 _MyHomePageState.build._incrementCounter (package:easy_pay/main.dart:71:24) E/flutter (16893):
> 
> I get this error when i call sendAdvancedUssd method. please solve this issue asap we are waiting. thank you.

Have you found any solution ? please.

**Comment by pkitatta** [comment]
I too have this problem.
