### ISSUE TITLE
Error When I Use MultiSession Ussd

### ISSUE THREAD

**Issue by OrionWambert** [EddieKamau/ussd_advanced#7]
I ran the project example but when I run the ussd with the single session and multi session method it generates an error 

```
E/flutter (18366): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'java.lang.String java.lang.String.toString()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toString()' on a null object reference
E/flutter (18366): 	at com.phan_tech.ussd_advanced.USSDController.isAccessibilityServicesEnable(USSDController.kt:244)
E/flutter (18366): 	at com.phan_tech.ussd_advanced.USSDController.verifyAccessibilityAccess(USSDController.kt:227)
E/flutter (18366): 	at com.phan_tech.ussd_advanced.USSDController.callUSSDInvoke(USSDController.kt:112)
E/flutter (18366): 	at com.phan_tech.ussd_advanced.UssdAdvancedPlugin.multisessionUssd(UssdAdvancedPlugin.kt:272)
E/flutter (18366): 	at com.phan_tech.ussd_advanced.UssdAdvancedPlugin.onMethodCall(UssdAdvancedPlugin.kt:158)
E/flutter (18366): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (18366): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (18366): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (18366): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (18366): 	at android.os.Handler.handleCallback(Handler.java:883)
E/flutter (18366): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/flutter (18366): 	at android.os.Looper.loop(Looper.java:214)
E/flutter (18366): 	at android.app.ActivityThread.main(ActivityThread.java:7726)
E/flutter (18366): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (18366): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
E/flutter (18366): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (18366): )
E/flutter (18366): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (18366): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (18366): <asynchronous suspension>
E/flutter (18366): #2      UssdAdvanced.multisessionUssd (package:ussd_advanced/ussd_advanced.dart:34:23)
E/flutter (18366): <asynchronous suspension>
E/flutter (18366): #3      _MyAppState.build.<anonymous closure> (package:flutter_learning/main.dart:81:36)
E/flutter (18366): <asynchronous suspension>
E/flutter (18366): 

```

**Comment by Hossny37** [comment]
I have faced same issue, after long debug the problem was in the minSDK of the packge, change it from 16 to 23,
please check my forked version it works normally.

**Comment by sakib556** [comment]
i have the same probmlem redmi note 11
